use crate::app::SignalApp;
use crate::storage::{StorageEncryptionMethod};
use egui::{Align, Layout, RichText};

static mut PASSWORD_INPUT: String = String::new();
static mut PASSWORD_CONFIRM: String = String::new();
static mut SELECTED_METHOD: Option<StorageEncryptionMethod> = None;
static mut ERROR_MESSAGE: Option<String> = None;

pub fn show(app: &mut SignalApp, ctx: &egui::Context) {
    egui::CentralPanel::default().show(ctx, |ui| {
        ui.with_layout(Layout::top_down(Align::Center), |ui| {
            ui.add_space(50.0);
            
            ui.heading(RichText::new("🔐").size(48.0));
            ui.add_space(15.0);
            
            ui.heading("Choose Encryption Method");
            ui.add_space(5.0);
            ui.label("Your messages and data will be encrypted at rest");
            ui.add_space(30.0);

            let selected = unsafe { &mut SELECTED_METHOD };
            let password = unsafe { &mut PASSWORD_INPUT };
            let confirm = unsafe { &mut PASSWORD_CONFIRM };
            let error = unsafe { &mut ERROR_MESSAGE };

            ui.horizontal(|ui| {
                ui.add_space((ui.available_width() - 400.0) / 2.0);
                ui.vertical(|ui| {
                    ui.set_width(400.0);

                    if ui.selectable_label(
                        *selected == Some(StorageEncryptionMethod::AutoGenerated),
                        RichText::new("🔑  Auto-Generated Key").size(16.0)
                    ).clicked() {
                        *selected = Some(StorageEncryptionMethod::AutoGenerated);
                        password.clear();
                        confirm.clear();
                        *error = None;
                    }
                    ui.label("    Random key stored in a file. Convenient but less secure.");
                    ui.add_space(15.0);

                    if ui.selectable_label(
                        *selected == Some(StorageEncryptionMethod::Password),
                        RichText::new("🔏  Password Protected").size(16.0)
                    ).clicked() {
                        *selected = Some(StorageEncryptionMethod::Password);
                        *error = None;
                    }
                    ui.label("    You enter a password each time. Most secure.");
                });
            });

            if *selected == Some(StorageEncryptionMethod::Password) {
                ui.add_space(20.0);
                ui.horizontal(|ui| {
                    ui.add_space((ui.available_width() - 300.0) / 2.0);
                    ui.vertical(|ui| {
                        ui.set_width(300.0);
                        ui.label("Password:");
                        ui.add(egui::TextEdit::singleline(password).password(true));
                        ui.add_space(10.0);
                        ui.label("Confirm Password:");
                        ui.add(egui::TextEdit::singleline(confirm).password(true));
                    });
                });
            }

            ui.add_space(20.0);

            if let Some(ref err) = *error {
                ui.colored_label(egui::Color32::RED, err);
                ui.add_space(10.0);
            }

            let can_continue = match *selected {
                Some(StorageEncryptionMethod::Password) => !password.is_empty() && password == confirm,
                Some(_) => true,
                None => false,
            };

            ui.add_enabled_ui(can_continue, |ui| {
                if ui.button("Continue").clicked() {
                    if let Some(method) = *selected {
                        let pwd = if method == StorageEncryptionMethod::Password {
                            Some(password.as_str())
                        } else {
                            None
                        };

                        match app.storage().setup_encryption(method, pwd) {
                            Ok(()) => {
                                password.clear();
                                confirm.clear();
                                *selected = None;
                                *error = None;
                                app.on_encryption_setup_complete();
                            }
                            Err(e) => {
                                *error = Some(format!("Setup failed: {}", e));
                            }
                        }
                    }
                }
            });

            if *selected == Some(StorageEncryptionMethod::Password) && !password.is_empty() && password != confirm {
                ui.add_space(5.0);
                ui.colored_label(egui::Color32::YELLOW, "Passwords do not match");
            }
        });
    });
}
